var questions = [
  new Question("What does padding refer to in the CSS box model?", 
    "It's the immediate neighbor of the content and gives the content room to breath",
    "A property of the box model that wraps the raw element boundry, before any padding or margins are added; It's like your house",
    "A property of the box model that allows you to display the outside borders of your element, which includes the content and the padding.",
    "This is like your force-field, it's not part of the element but it protects the element from it's neighbors; stay off my lawn!",
    "A"),
  new Question("What Does the Static position attribute do?", 
    "Makes the HTML element invisible",
    "Makes the HTML element boring looking",
    "Positions the element in it's default spot",
    "Positions the element in a user specified place",
    "C"),
  new Question("How do you create a conctructor function?", 
    "var Bear = function(height, name) { self.name; self.height};",
    "function Bear = function(height, name) { this.name; this.height};",
    "function Bear(height, name) { this.name; this.height};",
    "Bear function(height, name) { self.name; self.height};",
    "C"),
  new Question("Which of the folling isn't a primative data-type?", 
    "Integer",
    "Float",
    "Array",
    "Char",
    "C"),
];